-- Clear existing data
DELETE FROM "Watchlist";
DELETE FROM "Stock";
DELETE FROM "User";

-- Insert sample users (UUID auto-generated by Postgres)
INSERT INTO "User" (id, email, name, "createdAt", "updatedAt") VALUES
(gen_random_uuid(), 'john.doe@example.com', 'John Doe', NOW(), NOW()),
(gen_random_uuid(), 'jane.smith@example.com', 'Jane Smith', NOW(), NOW()),
(gen_random_uuid(), 'mike.wilson@example.com', 'Mike Wilson', NOW(), NOW());

-- Insert sample stocks
INSERT INTO "Stock" (id, symbol, name, "currentPrice", "dayHigh", "dayLow", volume, "lastUpdated", "createdAt", "updatedAt") VALUES
(gen_random_uuid(), 'RELIANCE.NS', 'Reliance Industries Limited', 2550.50, 2575.00, 2520.00, 12345678, NOW(), NOW(), NOW()),
(gen_random_uuid(), 'TCS.NS', 'Tata Consultancy Services Ltd', 3450.75, 3500.00, 3400.50, 9876543, NOW(), NOW(), NOW()),
(gen_random_uuid(), 'HDFCBANK.NS', 'HDFC Bank Limited', 1620.30, 1650.00, 1600.00, 8765432, NOW(), NOW(), NOW()),
(gen_random_uuid(), 'INFY.NS', 'Infosys Limited', 1655.40, 1680.00, 1630.00, 7654321, NOW(), NOW(), NOW()),
(gen_random_uuid(), 'ICICIBANK.NS', 'ICICI Bank Limited', 890.25, 910.00, 875.00, 6543210, NOW(), NOW(), NOW()),
(gen_random_uuid(), 'HINDUNILVR.NS', 'Hindustan Unilever Limited', 2505.60, 2550.00, 2480.00, 5432109, NOW(), NOW(), NOW()),
(gen_random_uuid(), 'BAJAJFINSV.NS', 'Bajaj Finserv Limited', 18000.75, 18250.00, 17850.00, 4321098, NOW(), NOW(), NOW()),
(gen_random_uuid(), 'MARUTI.NS', 'Maruti Suzuki India Limited', 8700.50, 8800.00, 8600.00, 3210987, NOW(), NOW(), NOW()),
(gen_random_uuid(), 'AXISBANK.NS', 'Axis Bank Limited', 770.40, 790.00, 755.00, 2109876, NOW(), NOW(), NOW()),
(gen_random_uuid(), 'LT.NS', 'Larsen & Toubro Limited', 2235.80, 2255.00, 2200.00, 1098765, NOW(), NOW(), NOW());

-- Example Watchlist inserts (using subqueries to map users & stocks)
INSERT INTO "Watchlist" (id, "userId", "stockId", "targetPrice", notes, "addedAt", "updatedAt")
SELECT gen_random_uuid(), u.id, s.id, 180.00, 'Waiting for earnings report', NOW(), NOW()
FROM "User" u, "Stock" s
WHERE u.email = 'john.doe@example.com' AND s.symbol = 'AAPL';

INSERT INTO "Watchlist" (id, "userId", "stockId", "targetPrice", notes, "addedAt", "updatedAt")
SELECT gen_random_uuid(), u.id, s.id, 300.00, 'Long term hold', NOW(), NOW()
FROM "User" u, "Stock" s
WHERE u.email = 'john.doe@example.com' AND s.symbol = 'TSLA';

INSERT INTO "Watchlist" (id, "userId", "stockId", "targetPrice", notes, "addedAt", "updatedAt")
SELECT gen_random_uuid(), u.id, s.id, 900.00, 'AI growth play', NOW(), NOW()
FROM "User" u, "Stock" s
WHERE u.email = 'john.doe@example.com' AND s.symbol = 'NVDA';